services:
  - type: web
    name: notmrp-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false   
      - key: JWT_SECRET
        sync: false   
      - key: JWT_EXPIRES_IN
        value: 7d
    plan: free
    region: singapore   
